### PR TITLE
bump alpine 3.14

### PR DESCRIPTION
**Pull request by andriisoldatenko**

### CODE REVIEW

**Review by kozlovic — CHANGES_REQUESTED** [review]
Thank you for the contribution. I would have done that for the next release, but thanks for helping out. You missed one reference I think: https://github.com/nats-io/nats-streaming-docker/blob/024b04f6c0d4658cf5751b21b48555bbe9280be5/0.22.0/scratch/Dockerfile#L2

**Comment by kozlovic** [comment]
@andriisoldatenko Since I am planning to do a release soon, I will merge this PR as-is and will follow up with the fix for the scratch image. Thanks.

**Review by kozlovic — APPROVED** [review]

**Comment by andriisoldatenko** [comment]
@kozlovic thanks a lot! and sorry for not replying

**Comment by andriisoldatenko** [comment]
@kozlovic do you want me to create new PR for fixing 
https://github.com/nats-io/nats-streaming-docker/blob/024b04f6c0d4658cf5751b21b48555bbe9280be5/0.22.0/scratch/Dockerfile#L2
?

**Comment by kozlovic** [comment]
@andriisoldatenko No worries and no need for new PR, I just fixed it. Thanks!

**Comment by kozlovic** [comment]
See https://github.com/nats-io/nats-streaming-docker/pull/33

**Pull request merged**
